### ISSUE TITLE
spurious error when loading project after closing another

### ISSUE THREAD

**Issue by axtimwalde** [trakem2/TrakEM2#16]
After closing a project, opening another project generates this, possibly consequence free, exception:
```
==================
ERROR:
java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.TokenMakerBase.addToken(TokenMakerBase.java:136)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4747)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4729)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4717)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.yylex(JavaTokenMaker.java:5180)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.getTokenList(JavaTokenMaker.java:4798)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.getTokenListForLine(RSyntaxDocument.java:431)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.getLineWidth(SyntaxView.java:306)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.calculateLongestLine(SyntaxView.java:110)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.refreshFontMetrics(RSyntaxTextArea.java:2084)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setFont(RSyntaxTextArea.java:2523)
	at org.fife.ui.rtextarea.RTextAreaUI.installDefaults(RTextAreaUI.java:363)
	at org.fife.ui.rtextarea.RTextArea.setUI(RTextArea.java:1639)
	at javax.swing.text.JTextComponent.updateUI(JTextComponent.java:338)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1233)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1248)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1224)
	at ini.trakem2.ControlWindow.setLookAndFeel(ControlWindow.java:131)
	at ini.trakem2.ControlWindow.<init>(ControlWindow.java:111)
	at ini.trakem2.ControlWindow.getInstance(ControlWindow.java:119)
	at ini.trakem2.Project.<init>(Project.java:279)
	at ini.trakem2.persistence.TMLHandler.startElement(TMLHandler.java:453)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at ini.trakem2.persistence.FSLoader.openFSProject(FSLoader.java:298)
	at ini.trakem2.Project.openFSProject(Project.java:554)
	at ini.trakem2.Project.openFSProject(Project.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at HandleExtraFileTypes.tryOpen(HandleExtraFileTypes.java:298)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:485)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:72)
	at ij.IJ.runUserPlugIn(IJ.java:221)
	at ij.IJ.runPlugIn(IJ.java:185)
	at ij.IJ.runPlugIn(IJ.java:174)
	at ij.io.Opener.openWithHandleExtraFileTypes(Opener.java:515)
	at ij.io.Opener.openImage(Opener.java:369)
	at ij.io.Opener.openImage(Opener.java:242)
	at ij.io.Opener.open(Opener.java:109)
	at ij.io.Opener.openAndAddToRecent(Opener.java:291)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:192)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:159)
	at java.lang.Thread.run(Thread.java:745)
==================
```

**Comment by acardona** [comment]
TrakEM2 doesn't use RSyntaxArea, so this has to do with the trigger of the `setLookAndFeel` that impacts an open Script Editor window, which then throws this error.
TrakEM2 shouldn't be setting the look and feel. This has been resolved partially or fully by @tferr recently with f722da49b0b8f22640cc4199c08dbfe8cfe97560
